2021-01-09 20:10:15,515 ERROR: Exception on /reset_password_request [POST] [in c:\users\racco\miniconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\racco\miniconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\racco\miniconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\racco\miniconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\racco\miniconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\racco\miniconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\racco\miniconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\BSUIR\stp\microblog_\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "E:\BSUIR\stp\microblog_\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\BSUIR\stp\microblog_\app\models.py", line 65, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-01-09 20:48:29,699 INFO: Microblog startup [in E:\BSUIR\stp\microblog_\app\__init__.py:47]
